#DEV environment
server:
  port: 8084
app:
  message: This is the property file to ${spring.application.name} specific to DEV
spring:
  datasource:
    driver-class-name: org.h2.driver
    url: jdbc:h2:mem:db:DB_CLOSE_DELAY=-1
    username: sa
    password: sa
